services:
  postgres:
    image: postgres:15-alpine
    container_name: orderservice_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d orders_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    image: orderservice_api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orderservice_api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=orders_db;Username=postgres;Password=postgres
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: